name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 8e28ae63-80aa-4742-9429-908e8ff4f11e
          GH_TOKEN: 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
