name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: "0 0 * * *"
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: itkhansunny/wakatime-action@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS : "True"
          SHOW_LOC_CHART: "False"
