name: Waka Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE : "en"
          SHOW_UPDATED_DATE : "True"
          UPDATED_DATE_FORMAT : "TZ='Asia/Dhaka' %d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE : "True"
          SHOW_TOTAL_CODE_TIME : "True"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_COMMIT : "True"
          SHOW_DAYS_OF_WEEK : "True"
          SHOW_LANGUAGE : "True"
          SHOW_OS : "True"
          SHOW_PROJECTS : "True"
          SHOW_TIMEZONE : "True"
          SHOW_EDITORS : "True"
          SHOW_LANGUAGE_PER_REPO : "True"
          SHOW_SHORT_INFO : "True"
          SHOW_LOC_CHART : "True"
          SYMBOL_VERSION : 2
